# Generated by Django 5.0.7 on 2024-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('employee', 'Employee'), ('user', 'User')], max_length=15, null=True),
        ),
    ]
