# Generated by Django 5.0.7 on 2024-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='business',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='interrest',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('user', 'User')], default=None, max_length=15, null=True),
        ),
    ]
