# Generated by Django 5.0.7 on 2024-08-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_business_useraccount_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='interrest',
            new_name='interest',
        ),
    ]
